// ===========================================================================
//  sim_stubs.v
//  Simulation stub modules for Vivado PCIe IP and other IPs
//  These are placeholder black-box declarations for simulation only.
//  NOT used in synthesis/implementation (UsedIn = simulation only).
// ===========================================================================

// Stub for pcie_7x_0 IP (used in simulation when IP is not generated)
// In actual synthesis, Vivado uses the real generated IP netlist.

`timescale 1ns / 1ps

// Empty file - PCIe IP stubs are auto-generated by Vivado during simulation.
// This file exists to satisfy Vivado project file references.
