# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/dukehhu/Desktop/1121/constraints.xdc

# IP: ip/pcie_7x_0/pcie_7x_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pcie_7x_0 || ORIG_REF_NAME==pcie_7x_0} -quiet] -quiet
